### PR TITLE
Draft PR for Dashboard layout tool

### PR DESCRIPTION
**Pull request by KazuhiroItoh**
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed change
I created a pull request(draft) for the dashboard layout tool.  
There are the following limitations.  
-The width of the group can be changed up to 12. If you set a larger width, it will not work properly.  
-Supports only dashboard standard nodes.  
-The widget on the layout screen may not be able to operate.In that case, please refresh on the browser screen or try restarting the browser.  

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
Hi - so how do I invoke this ? I have checked it out, npm installed, and gulp to build it... but I can't see any difference yet... where is the magic ? or how do i access it ? thanks

**Comment by HiroyasuNishiyama** [comment]
Hi, After adding some nodes to a tab,  **Layout** button appear when mouse-over on tab item in layout sidebar.

layout-button

When **Layout** button is selected, layout editor will apper over editor window.

layout-editor

**Comment by dceejay** [comment]
That works well ! Initial impressions good.

**Comment by dceejay** [comment]
Some thoughts... 
1) could the internal labels be the node label || node name  (rather than the type) - so they match the name in the current sidebar ?  So Button 1  Button 2   etc rather than all being ui_button.  
2) Question (probably for @knolleary ) - can the name of the Tab being edited be put in the grey space top left ? (or is that 100% for buttons ?)
image
3) could there be some sort of faint grid lines shown ? - though I realise the groups are shown independently at the moment, so maybe only inside the groups ?
4) can / could (one day) the groups be re-ordered this way also ?  I know we probably can't replicate the complete responsive layout of the current dashboard (and nor should we) - but may at least be able to move them left right order ? (I think gridstack allows for nested boxes - but yes a) this could be hard and b) could give unrealistic expectation of how final layout may be)

I'm certainly happy enough that we should consider merging it fairly soon, even with the caveats you already mention.

**Comment by dceejay** [comment]
The lists of widgets handled is hardcoded - https://github.com/node-red/node-red-dashboard/blob/1833e048e45ae9f28c56cab1767dda1204bba814/nodes/ui_base.html#L330
That should really be the same regex we use for the sidebar 

    `if (/^ui_/.test(node.type) && node.type !== 'ui_link' && node.type !== 'ui_toast' && node.type !== 'ui_ui_control') {`

**Comment by HiroyasuNishiyama** [comment]
> 1. could the internal labels be the node label || node name  (rather than the type) - so they match the name in the current sidebar ?  So Button 1  Button 2   etc rather than all being ui_button.
> 2. Question (probably for @knolleary ) - can the name of the Tab being edited be put in the grey space top left ? (or is that 100% for buttons ?)

For item 1 & 2, we will try to change implementation according to your suggestion.

> 3. could there be some sort of faint grid lines shown ? - though I realise the groups are shown independently at the moment, so maybe only inside the groups ?

Need some research, then try to implement a feature to show grid line. 

> 4. can / could (one day) the groups be re-ordered this way also ?  I know we probably can't replicate the complete responsive layout of the current dashboard (and nor should we) - but may at least be able to move them left right order ? (I think gridstack allows for nested boxes - but yes a) this could be hard and b) could give unrealistic expectation of how final layout may be). For now at least they have names so the user knows which is which.
>    I like the way the groups scale if you have lots of them though. Works nicely - though I can see this would be a reason not to do a grid (item 3 :-)

Also need some research.
We think we should add a button that rearrange order of groups because 
nesting feature of `Gridstack.js` do not allow drag&drop between nested widgets.  

> I'm certainly happy enough that we should consider merging it fairly soon, even with the caveats you already mention.

**Comment by dceejay** [comment]
Great - please implement 1 & 2.  See if 3 is possible. 4 leave until later/next version.

**Comment by dceejay** [comment]
Hi, any updates on this PR ?

**Comment by HiroyasuNishiyama** [comment]
@dceejay Sorry.  Due to our internal situation, it will take some more time.

**Comment by dceejay** [comment]
No worries. Let me know as and when. In meantime I may push out some small fixes.

**Comment by KazuhiroItoh** [comment]
I updated the dashboard layout tool.
- Changed the maximum group width from 12 to 30.
- Supported additional widgets.
- Correction request (1 & 2, 3 correction reflected).
- Other corrections related to display.

There are the following limitations.
There is an issue with the incorrect order in the edited layout tab, and we are investigating a correction.

**Comment by dceejay** [comment]
Just tried this against latest NR dev branch. not sure what's up but the layout editor tray doesn't open

**Comment by dceejay** [comment]
I get
VM8540:1585 Uncaught TypeError: Cannot read property ‘removeAll’ of undefined
   at Object.open (<anonymous>:1585:42)
   at showTray (red.js:25107)
   at Object.show (red.js:25179)
   at HTMLAnchorElement.<anonymous> (<anonymous>:1692:34)
   at HTMLAnchorElement.dispatch (vendor.js:2)
   at HTMLAnchorElement.v.handle (vendor.js:2)

from
image

**Comment by KazuhiroItoh** [comment]
Seemingly, a gridstack package wasn't loaded. Please make sure that there are gridstack-extra.min.css and gridstack.min.css in the dist\css folder. And also gridstack.jQueryUI.min.js ,  gridstack.min.js, gridstack.min.map annd lodash.min.js   in the dist\js folder. Please let me know the version of node.js, the browser and its version.

**Comment by dceejay** [comment]
They are there 
image

but they should be being packed into the minified files by the gulp step unless explicitly needed outside for some reason ?

I'm on Mac - nodejs 10.15.3 - Chrome 75.0.3770.51

**Comment by KazuhiroItoh** [comment]
無題
We confirmed that gridstack worked correctly on Node.js 8.11.1 on Windows 10 and we used Chrome. Unfortunately we don't have the same envrionment as yours. Could you give me a little more time to confirme that by reproducing the same environment.

**Comment by dceejay** [comment]
Are you running is dev mode or production mode ? The files will need to be in the minified files for production

**Comment by KazuhiroItoh** [comment]
>but they should be being packed into the minified files by the gulp step unless explicitly needed outside 
>for some reason ? They seem to be missing from the index.html.

These files are not packed into a minified files. Just acquire them by npm command and deploy under the dist folder.

**Comment by KazuhiroItoh** [comment]
>Are you running is dev mode or production mode ? The files will need to be in the minified files for production

I started by node-red command without any arguments when I confirmed gridstack worked correctly. I think running on production mode. Including running modes, I'll contact you as soon as I finish confirming.

**Comment by dceejay** [comment]
To be sure I used npm pack to create the .tgz file then installed it separately.
I know they aren't packed into the minified file - but I think they should be... If they are put into index file correctly they will be.

**Comment by dceejay** [comment]
Ah I think the issue is that you are loading tthings in th html like <link rel="stylesheet" href="./ui_base/css/gridstack.min.css"> - If you load them correctly via index then they would be there ok.

**Comment by KazuhiroItoh** [comment]
I mistakenly pulled the project from the master branch in the previous confirmation. Getting from the latest dev branch, I confirmed the same error occurred on Windows 10. The cause of the error is the "specification change" made in the dev branch. There are three issues, and I'm considering measures.

(1) The class name "editor-tray-body" has been changed to "red-ui-tray-body" in the latest dev branch. The class had been referred in the Node-RED editor tray. This caused the error and the editor didn't start up. I'm considering the following modifications. Would it be acceptable?

```
 var nodeRedVersion = RED.settings.version.split('.');  
 var trayBody;
 if (Number(nodeRedVersion[0]) < 1) {
     trayBody = tray.find('.editor-tray-body'); // major version is less than 1
 } else {
     trayBody = tray.find('.red-ui-tray-body'); // major version is more than 1
 }
```
(2) There is no Bootstrap in the latest dev branch. Gridstack uses Bootstrap to arrange discrete regions (each layout group) horizontally. Could you make Bootstrap available in the dev branch? 

(3) jQuery has been upgraded. There is jQuery UI v1.12.1 in the latest dev branch and it conflicts with and Bootstrap v2.3.2. The icon which indicates up and down of "spinner" disappeared. Instead of "spinner", I'm considering to use "elementSizer" or "typedInput" Node-RED provides.

**Comment by KazuhiroItoh** [comment]
I updated the dashboard layout tool.
This update does not work on node RED dev branch.
Please refer to the previous comment for details.

**Comment by dceejay** [comment]
I can't see bootstrap as a dependency of gridstack ? - Is it really mandatory ? (We won't be adding bootstrap back into dev just for this - as it pollutes the entire page - if we must have it we would need to wrap it for use in dashboard only.)

Re spinner - there is also one in jquery-ui if needed. 

Nick will reply re the traybody - (will make an alias for the old name so it will still work in dev)

**Comment by dceejay** [comment]
f it's just css we need then maybe we can just add our own based of the few required classes ? or is there a lot more missing ?

``` 
.container-fluid {
  width: 100%;
  padding-right: 15px;
  padding-left: 15px;
  margin-right: auto;
  margin-left: auto;
}

.row {
  display: flex;
  flex-wrap: wrap;
  margin-right: -15px;
  margin-left: -15px;
}
```
(Latest version of bootstrap seems to set .row to be fluid anyway...)

**Comment by knolleary** [comment]
I've restored `editor-tray-body` as a class on the tray body element to avoid breaking things - but it is deprecated. That will keep things working for the time being, but new code should use `red-ui-tray-body` moving forward.

For backwards compatibility, you can use `$(".red-ui-tray-body,.editor-tray-body")` to select either class without needing to check the specific version.

For the spinner, use the jQuery UI spinner - for example, as used by the Function node: https://github.com/node-red/node-red/blob/dev/packages/node_modules/%40node-red/nodes/core/core/80-function.html#L43

Looking at gridstack, I'm slightly confused. Their requirements are listed here: https://github.com/gridstack/gridstack.js#requirements
 - jQuery > 3.1.0
 - jQuery UI 1.12.0

both of which the `dev` branch satisfies. No mention of bootstrap - but also, given the jQuery > 3.1 requirement, not sure how this has been working against the current Node-RED release that has jQ 1.x.

**Comment by KazuhiroItoh** [comment]
Dave, Nick
Thank you very much.
I was able to substitute CSS for Bootstrap by the advice you had given me. I confirmed that searching for trayBody element works correctly in the  dev and master branches. In addition I fixed other bugs.

-the details of the revision-
(1) Layout tool works correctly in the dev and master branches by appending "OR" condition. 

(2)I defined CSS to arrange layout groups horizontally, and it works correctly without using Bootstrap. 

(3) Bug fix: Deployment fails when you use Internet Explorer 11.  The cause of it is that "fill()" method is not supported. I have fixed to avoid using the method. 

-limitations-
When you use Node-RED v1.0.0-beta2 on Internet Explorer 11, you cannot edit layout due to the following problems. 

(1) Relocating or resizing of nodes does not work properly. 

(2) Internet Explorer 11 freezes when you move a node between groups. ( no error on browser console ) This error doesn't occur on Node-RED v0.20.5 on Internet Explorer 11.

> Looking at gridstack, I'm slightly confused. Their requirements are listed here: 

That's as you pointed out, the version of jQuery which has been adopted in v1.0.0 seems appropriate. The version is different from the version of jQuery which has been adopted in v0.20.5, but it works properly.

**Comment by dceejay** [comment]
Soooo much better - thanks for those.

One thing I notice - if I resize the grid then all the nodes that were previously auto size now get set to a fixed size. Not sure this is quite the right behaviour, though I can understand it does sort of make sense.  Also if all the widgets are auto sized I think I should be able to shrink the group width without having to manually size them smaller first.

Likewise  when I drag a widget from one group to another I would expect the old group to shuffle up and remove the hole left behind without having to reposition everything manually. (like the widgets in the new group shuffle to make space for the new widget being dropped)

But yes - definitely heading in the right direction now.

**Comment by KazuhiroItoh** [comment]
We confirmed the 2 requests.We will modify the programme to support "auto". See below.

**First:**
・Adding the button which indicates "auto" or "fix" on the widget.
・The case you select 'auto', the width of a widget is changed automatically adhering to the width of its group.
auto-fix
**Second:**
If we deny the float option of gridstack, spaces between widgets are removed when you move a widget. You can not design a layout freely because you can not insert any spaces between widgets.
We reckon that we can provide freedom of layout, which allows to insert spaces, by enabling the float option.

Currently we are considering the way how to implement for supporting 'auto' mode.
We are planning to modify from the end of this month to the next month, but regarding this PR, I would like to release it as it is for now. Please consider it.

**Comment by dceejay** [comment]
Re 1st - great - looks good... yes - switching it to auto mode should let it "expand" to take the space it needs.
Re 2nd - yes - we need to be able to insert spaces. Maybe (just a suggestion - I may be wrong, feel free to disagree) - only when you move (or resize) a widget it becomes fixed size (so it can then have spaces around it) - and once placed you can if necessary re-click the auto. If you don't move (or resize) a widget it should remain auto sized, if it was already auto). Does that make sense ?

**Comment by KazuhiroItoh** [comment]
A toggle button located on the upper right as shown in the attached figure in the current proposal, and I implemented. It provides the function to switch the modes to resize in gridstack.
auto
I have considered the proposal from you. If allows users to resize in the automatic resizing mode, it's difficult for users to recognise the mode when they edit on the editor.
By switching the mode by hand, users could recognise the difference between the automatic and manual resize mode. That helps users to avoid operation mistakes.

**Comment by KazuhiroItoh** [comment]
Supported "Automatic mode" of widget size setting.
In the case you select "Automatic mode", each widget's width and height are automatically determined according to the width of its group and the node setting.
You can switch to "Manual mode" with the toggle switch at the top right of the widget.

**Comment by dceejay** [comment]
That is SO much better !
I think we are now down to small style things... (feel free to disagree)
I think the auto/manual icon should probably be the lock / unlock icons, and ideally align the resizer grab arrow icon with the lock/unlock icon.
Also I think the overall group column should have a slight background colour (maybe #f8f8f8f).
And finally I think it would be nicer if the width box aligned to the right of the grid box - not the overall column right... 
image

**Comment by dceejay** [comment]
Can you also look at the locale merge conflicts ? 
Once done I think we can move this to a full PR, so we can hopefully merge it next week.

**Comment by dceejay** [comment]
Yes - all good with me. Are you able to change the type to be a full lPR rather than Draft. 
Can you look at the merge conflicts - especially the ja locale ones :-)  
Thanks

**Comment by KazuhiroItoh** [comment]
I rebased on the latest master branch.
I forgot to set the draft PR, I think that it is in the state of full PR.
please confirm.

**Comment by dceejay** [comment]
Aha - yes - no wonder I couldn't find the button to make it a full PR :-)
Do you want to add yourself to the contributors in package.json ?

**Comment by KazuhiroItoh** [comment]
Thank you very much. I want to add it.

**Comment by dceejay** [comment]
OK - just update the PR one more time to add your details.

**Comment by KazuhiroItoh** [comment]
I updated the package.json.

**Comment by dceejay** [comment]
Thank you very much for this... It is a great new feature.

**Comment by wongnam** [comment]
I really like this layout tool. Thanks.
Although I know this is a bit late, but I want to comment a bit that it has not adjusted for spacer.

**Pull request merged**
