### PR TITLE
support specifying widget/group size by numeric value

### PR DESCRIPTION
**Pull request by HiroyasuNishiyama**
Add an interface for specifying a size of widgets/groups using numeric values. 
When the size label (e.g. 3 x 4) of a drag mode popup is clicked, the interface switch from drag mode to text input mode.

### CODE REVIEW

**Comment by dceejay** [comment]
This works really well... so happy to merge it...
Only thought... is it "obvious" enough that people can click on the numbers if they need to. Does it need a visual cue ? 

(I'm happy as it is - just asking for other opinions before merging).

**Comment by HiroyasuNishiyama** [comment]
Hi, 
I added a function to show an underline to the size text on mouse over.
Also added a function to fix size by pressing ENTER key, and minor correction of text box size.

**Comment by dceejay** [comment]
Hi - for some reason the CLA check has failed - are you using your correct userid ?

**Comment by HiroyasuNishiyama** [comment]
Hmm.  It seems that I committed changes with my personal ID.
I will try deleting the pull request first and register again.
Sorry to bother you.

**Pull request closed without merging**
