### PR TITLE
UI Template: possibility to define template content via msg.template

### PR DESCRIPTION
**Pull request by camilleb**
This pull request adds the possibility to set the template of the ui_template node via `msg.template`.  This can be useful for different scenarios.  The most useful one is the ability to switch templates dynamically.
If `msg.template` is not present the node will behave as it normally would.  The presence of `msg.template` overrides the template defined in the node's properties.

Here's an example flow for you to test:

```json
[
    {
        "id": "4ecd0a42.6df6d4",
        "type": "tab",
        "label": "UI Template example"
    },
    {
        "id": "4ccb23c4.d3928c",
        "type": "ui_template",
        "z": "4ecd0a42.6df6d4",
        "group": "d4af9b5e.b05968",
        "name": "",
        "order": 0,
        "width": "6",
        "height": "5",
        "format": "",
        "storeOutMessages": true,
        "fwdInMessages": true,
        "x": 940,
        "y": 340,
        "wires": [
            []
        ]
    },
    {
        "id": "c017861f.6b3358",
        "type": "template",
        "z": "4ecd0a42.6df6d4",
        "name": "Angular template example",
        "field": "template",
        "fieldType": "msg",
        "format": "handlebars",
        "syntax": "plain",
        "template": "<script>\nthis.scope.turnOn = function (obj) {\n  alert(`Turn on ${obj.name}`);\n}\nthis.scope.turnOff = function (obj) {\n  alert(`Turn off ${obj.name}`);\n}\n</script>\n<md-content>\n    <md-list class=\"md-dense\" ng-repeat=\"(cat, list) in msg.payload\">\n        <md-subheader class=\"md-no-sticky\">{{cat}}</md-subheader>\n        <md-list-item ng-repeat=\"item in list\">\n          <p>{{item.name}}</p>\n          <md-button class=\"md-raised\" ng-click=\"turnOn(item)\">ON</md-button>\n          <md-button class=\"md-raised\" ng-click=\"turnOff(item)\">OFF</md-button>\n        </md-list-item>\n    </md-list>\n</md-content>\n",
        "x": 320,
        "y": 100,
        "wires": [
            [
                "600306c3.bb4558"
            ]
        ]
    },
    {
        "id": "600306c3.bb4558",
        "type": "template",
        "z": "4ecd0a42.6df6d4",
        "name": "some equipments",
        "field": "payload",
        "fieldType": "msg",
        "format": "json",
        "syntax": "plain",
        "template": "{\n  \"projectors\": [\n    {\n      \"id\": \"1\",\n      \"name\": \"proj-01\"\n    },\n    {\n      \"id\": \"2\",\n      \"name\": \"proj-02\"\n    },\n    {\n      \"id\": \"3\",\n      \"name\": \"proj-03\"\n    },\n    {\n      \"id\": \"4\",\n      \"name\": \"proj-04\"\n    },\n    {\n      \"id\": \"5\",\n      \"name\": \"proj-05\"\n    }\n  ],\n  \"screens\": [\n    {\n      \"id\": \"1\",\n      \"name\": \"screen-01\"\n    },\n    {\n      \"id\": \"2\",\n      \"name\": \"screen-02\"\n    },\n    {\n      \"id\": \"3\",\n      \"name\": \"screen-03\"\n    }\n  ]\n}\n",
        "x": 590,
        "y": 140,
        "wires": [
            [
                "5ef42751.385a08"
            ]
        ]
    },
    {
        "id": "eaada532.7e45f8",
        "type": "inject",
        "z": "4ecd0a42.6df6d4",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 100,
        "y": 100,
        "wires": [
            [
                "c017861f.6b3358"
            ]
        ]
    },
    {
        "id": "5ef42751.385a08",
        "type": "json",
        "z": "4ecd0a42.6df6d4",
        "name": "",
        "x": 750,
        "y": 140,
        "wires": [
            [
                "4ccb23c4.d3928c"
            ]
        ]
    },
    {
        "id": "5c61f535.96617c",
        "type": "template",
        "z": "4ecd0a42.6df6d4",
        "name": "An other template",
        "field": "template",
        "fieldType": "msg",
        "format": "handlebars",
        "syntax": "plain",
        "template": "<div ng-repeat=\"(cat, list) in msg.payload\">\n    {{ cat }}\n    <ul>\n        <li ng-repeat=\"item in list\">\n            {{item.name}}\n        </li>\n    </ul>\n</div>\n",
        "x": 350,
        "y": 180,
        "wires": [
            [
                "600306c3.bb4558"
            ]
        ]
    },
    {
        "id": "af9d5f08.7e6a6",
        "type": "inject",
        "z": "4ecd0a42.6df6d4",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 100,
        "y": 180,
        "wires": [
            [
                "5c61f535.96617c"
            ]
        ]
    },
    {
        "id": "71dd2f7d.ea768",
        "type": "comment",
        "z": "4ecd0a42.6df6d4",
        "name": "Change template dynamically",
        "info": "",
        "x": 140,
        "y": 40,
        "wires": []
    },
    {
        "id": "dcf95244.d6798",
        "type": "comment",
        "z": "4ecd0a42.6df6d4",
        "name": "Just update msg.payload",
        "info": "",
        "x": 130,
        "y": 280,
        "wires": []
    },
    {
        "id": "d81dcb31.887898",
        "type": "template",
        "z": "4ecd0a42.6df6d4",
        "name": "other equipments",
        "field": "payload",
        "fieldType": "msg",
        "format": "json",
        "syntax": "plain",
        "template": "{\n  \"projectors\": [\n    {\n      \"id\": \"1\",\n      \"name\": \"proj-01\"\n    },\n    {\n      \"id\": \"2\",\n      \"name\": \"proj-02\"\n    },\n    {\n      \"id\": \"3\",\n      \"name\": \"proj-03\"\n    }\n  ],\n  \"screens\": [\n    {\n      \"id\": \"1\",\n      \"name\": \"screen-01\"\n    },\n    {\n      \"id\": \"2\",\n      \"name\": \"screen-02\"\n    },\n    {\n      \"id\": \"3\",\n      \"name\": \"screen-03\"\n    },\n    {\n      \"id\": \"4\",\n      \"name\": \"screen-04\"\n    },\n    {\n      \"id\": \"5\",\n      \"name\": \"screen-05\"\n    }\n  ]\n}\n",
        "x": 350,
        "y": 340,
        "wires": [
            [
                "4bd28e05.f84dc"
            ]
        ]
    },
    {
        "id": "4bd28e05.f84dc",
        "type": "json",
        "z": "4ecd0a42.6df6d4",
        "name": "",
        "x": 650,
        "y": 340,
        "wires": [
            [
                "4ccb23c4.d3928c"
            ]
        ]
    },
    {
        "id": "cb9adbe.c544428",
        "type": "inject",
        "z": "4ecd0a42.6df6d4",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "x": 100,
        "y": 340,
        "wires": [
            [
                "d81dcb31.887898"
            ]
        ]
    },
    {
        "id": "d4af9b5e.b05968",
        "type": "ui_group",
        "z": "",
        "name": "Default",
        "tab": "5d32be74.63179",
        "disp": true,
        "width": "6"
    },
    {
        "id": "5d32be74.63179",
        "type": "ui_tab",
        "z": "",
        "name": "Home",
        "icon": "dashboard",
        "order": 6
    }
]```

### CODE REVIEW

**Comment by dceejay** [comment]
Hmm - not sure. If you need to change the template why not make the actual ui_template a default - I'll pass everything in on msg.payload one... and then have a preceeding normal template (or templates)  that adorns the payload with anything you need there ?

**Comment by camilleb** [comment]
The aim of this is to be able to only pass angular template structure in `msg.template`, and populate this template with data defined in `msg.payload`. So when some data changed, angular data binding refresh only what it needs. 

If we use `msg.payload` to pass the template with all data inside, we have to recompile the entire template every time a data changed.

**Comment by natcl** [comment]
This would be very useful for our use case as we are building nodes that would dynamically inject both the actual angular template and the payload.
The nice thing is that it doesn't affect current functionality at all.

**Comment by dceejay** [comment]
Sure, will look at it soon. Just sorting some core nodes.

**Comment by natcl** [comment]
Thanks ! :)

**Pull request merged**
