### PR TITLE
Fix join function undefined handling

### PR DESCRIPTION
**Pull request by doino-gretchenliev**
Description: https://github.com/node-red/node-red-dashboard/issues/517

### CODE REVIEW

**Comment by knolleary** [comment]
Hi - can you provide a bit more of a description of what this is fixing? What scenario does it address? How can we verify what it is doing?

**Comment by doino-gretchenliev** [comment]
> Hi - can you provide a bit more of a description of what this is fixing? What scenario does it address? How can we verify what it is doing?

I was just posting a issue, describing the problem.

**Comment by dceejay** [comment]
Hi are you able to sign/click the CLA so we can merge this fix ?

**Comment by doino-gretchenliev** [comment]
> Hi are you able to sign/click the CLA so we can merge this fix ?

The commit message author is now fixed, so CLA passed successfully.

**Comment by dceejay** [comment]
Many thanks

**Pull request merged**
