### PR TITLE
changed all nodes to use common category translation in ui_base.json

### PR DESCRIPTION
**Pull request by heikokue**
With this change all dashboard nodes uses the common category translation ui_base.label.category.
I hope, it's OK so.

### CODE REVIEW

**Comment by heikokue** [comment]
Another way could be to expand the list of core categories with common/popular used names (see editor-client\src\js\ui\palette.js: var coreCategories = [ 'subflows', ...
and to add their translations in locales\de\editor.json palette.label.???
The following categorys may be added to the list:
- dashboard
- time
- weather
- transport
- mobile
- fitness
- location
- utility

Shall I do a PR against core to demonstrate, what I think?

**Comment by dceejay** [comment]
If you are going to  change the structure then you also need to change the ja files as well.

And no I think dashboard translations should remain in the dashboard project.
Only translations actually needed by the core should be in core.

**Comment by heikokue** [comment]
ok, do I still have to change something here (this PR)?
here (dashboard) we have only the palette categories 'config' and 'dashboard'.
with this PR the translation of 'dashboard' is now central handled in the locales ui_base.json

**Comment by dceejay** [comment]
At first glance it looks ok. will check more thoroughly later.

**Pull request merged**
