### PR TITLE
Pelis final dropdown

### PR DESCRIPTION
**Pull request by pelis**
Hope this is now the proper way...
The way it should work:
dropdown may now receive an input message which contains:
- an array of new option entries
  in this case beforeEmit () will transform the option list to an array of Objects: [{label: "l1", value: "v1"}, ...]
- an array of label/value objects
I am also setting such new values in the control (back-end) so that a 'replay' will reflect such new entries

Attached is a sample flow to test things...
[red-dashboard-dropdown.txt](https://github.com/node-red/node-red-dashboard/files/407120/red-dashboard-dropdown.txt)

In the end it turned out to be somewhat tricky...

### CODE REVIEW

**Comment by dceejay** [comment]
Hi - have applied tis as-is for now... the good news is it hasn't broken anything...
bad is that the example flow you posted doesn't seem to work - I'm not seeing any changes in the UI.

**Comment by dceejay** [comment]
Aha - the first example passes in an object not an array of objects... 
However once "fixed" it then does only give one choice - but selecting it does not send anything.

**Comment by dceejay** [comment]
I'm not sure that the options should be passed through on change. It means the user then has to filter out updates from user input. If the input is invalid we can use node.warn or node.error to alert in the editor UI if needs be.

Finally - while internally we use an array of objects to hold the options... is that the easiest way to pass them in ? if auto-generating a list would people do it that way naturally ? or would an array of just {"label":"value"} objects we easier / more natural ?

**Comment by pelis** [comment]
good point, {"label":"value"} seems more natural. Do you think we should keep allowing to enter an array of values? Maybe just {"label":"value"} is fine - reduces code anyway.

How/where should such changes be done since it is now merged? 
(I don't want to mess arround again :-))

**Comment by dceejay** [comment]
Don't mind - just thought it may be simpler to generate automatically from some list or other. Could support both I suppose - though now is the time to choose...
I'll see if @natcl from Issue #22 has an opinion also.

I definitely don't like the options passing through though... can that be stopped ? What is the use case for that ?

Re updates - well you should just resync from master and do another change / PR . Should be easy now :-)

**Comment by natcl** [comment]
I also agree, I think an array of {"label":"value"} would be the easiest !

**Comment by knolleary** [comment]
Wouldn't the absolute easiest be: ["one","two","three"]?

No reason not to support both strings and {label:value} objects as they are
trivially distinguishable.

**Comment by natcl** [comment]
And in the case of an array of strings, both label and value would be the same ?

**Comment by dceejay** [comment]
and set label == value in that case ?
(or indeed should it be      {"value":"label"}  order instead.... eg like key and thing[key] )

**Comment by pelis** [comment]
"I definitely don't like the options passing through though... can that be stopped ? What is the use case for that ?"
PL: Yes think so - maybe just pass the new selection (value) to payload. I thought that the recipient of the message would want to know that there is a new options list and could - for example - load another data set for a chart display or whatever. We could actually pass the value in payload and the options in a different member of msg. In that case the receiving node would NOT have to care about whether the new value came from an options change or a selection - the msg object just would provide additional members. Any suggestions what we would pass as value in case of invalid options?
If you ask me, the dropdown really makes the most sense in combination with the 'meOnly' idea that I brought up earlier... :-). If you have multiple clients - would all clients really want to be updated when one client selects something?

“Wouldn't the absolute easiest be: ["one","two","three"]?”
PL: That’s already implemented as the ‘optional’ way to provide new options. In this case label == value. As discussed here as well, we could provide both ways ({label:value} and ["one","two","three"]) – see other comments.

“And in the case of an array of strings, both label and value would be the same ?”
PL: Yes, not only for array of strings, also for array of numbers – I wouldn’t try to distinguish that one – as mentioned above, this is already implemented.

**Comment by dceejay** [comment]
Yes - only output message should (IMHO) be one the user selects. If there is a new list being sent that can also be wired to some other place in parallel - it doesn't have to go via the dropdown node.
Invalid options should be ignored by the node, and return a node.error event (which can then be caught with the catch node if required)
Re - meOnly - yes - we will definitely like to think some more on that... and yes the (or all) widget inputs may need to be identified by user/session.  But when something updates the list of choices for the select that should probably be for all users ???

**Comment by pelis** [comment]
In most cases I would agree regarding the actual list of options.

Example, where it could be useful:
When a dropdown depends on the selection of another dropdown.
Dropdown one: Select a Region
Dropdown two: Should only contain - say customers of the selected region.

If - in the far future :-) - something like passport / user-control could be introduced - then you would want to display select options only that a user is allowed to select. But this one certainly is out of scope for the moment I guess.

**Pull request merged**
