### PR TITLE
Add option 'send on focus leave' for ui_text_input node

### PR DESCRIPTION
**Pull request by ddresch**
**Situation** 
The current version of the 'ui_text_input' node sends it's value in case of a focus leave or on enter / tab press.

**Use Case**
For a use case where a user is writing text in a `ui_text_input` and at some point needs to click a button (leave the focus) the half written text will be send.

This PR adds a new option / checkbox to the `ui_text_input` configuration which allows for disabling the sending.

send-on-leave-option

**Example Flow**
```json
[{"id":"deb3977e.c7e4a","type":"ui_text_input","z":"56abfb54.fa813c","name":"","label":"Send on focus leave","tooltip":"","group":"73f6eec8.70c308","order":0,"width":0,"height":0,"passthru":true,"mode":"text","delay":"0","topic":"","sendonblur":true,"topicType":"str","x":400,"y":200,"wires":[["10c20195.d951d6"]]},{"id":"cf3f9ed7.0c6fb8","type":"ui_text_input","z":"56abfb54.fa813c","name":"","label":"Delay 3 ms and send on leave ","tooltip":"","group":"73f6eec8.70c308","order":0,"width":0,"height":0,"passthru":true,"mode":"text","delay":"3","topic":"","sendonblur":true,"topicType":"str","x":370,"y":140,"wires":[["10c20195.d951d6"]]},{"id":"10c20195.d951d6","type":"ui_text","z":"56abfb54.fa813c","group":"73f6eec8.70c308","order":1,"width":0,"height":0,"name":"","label":"Output","format":"{{msg.payload}}","layout":"row-spread","x":610,"y":200,"wires":[]},{"id":"e9c03edc.8dc5a","type":"ui_text_input","z":"56abfb54.fa813c","name":"","label":"Don't send on leave","tooltip":"","group":"73f6eec8.70c308","order":3,"width":0,"height":0,"passthru":true,"mode":"text","delay":"3","topic":"","sendonblur":false,"topicType":"str","x":400,"y":260,"wires":[["10c20195.d951d6"]]},{"id":"73f6eec8.70c308","type":"ui_group","name":"Default","tab":"2e9ff58d.6dbab2","order":1,"disp":true,"width":"6","collapse":false},{"id":"2e9ff58d.6dbab2","type":"ui_tab","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]```

### CODE REVIEW

**Comment by dceejay** [comment]
rather than add a whole new form can you not make the ng-blur conditional ? (eg see https://stackoverflow.com/questions/38995870/how-to-use-ng-if-and-ng-blur-together) 

plus need to sign the CLA please...

**Comment by ddresch** [comment]
Thanks for this SO question link, will try to use it that way. I'm not an Angular user and this was the simplest way to adapt the current setup :)

About the CLA I already signed it yesterday and it is still showing "Pending". When I try to sign it shows:

cla-signed

You know about a "trick" how to fix this?

**Comment by ddresch** [comment]
Removed the third template and used the inline condition for ng-blur. 

About CLA the problem is the mail I used for the commit and the one I use on Github. Now the two match but CLA assist is still using the old one (which is not even available in my github account anymore). Need to look into this again. The easiest way is probably doing a fresh PR?

**Comment by dceejay** [comment]
Sadly yes. Redoing PR is usually the simplest way even if fugly.

**Comment by ddresch** [comment]
Okay then I close this one and reopen new one.

**Pull request closed without merging**
