### PR TITLE
update gridstack to 0.6.4

### PR DESCRIPTION
**Pull request by HiroyasuNishiyama**
As discussed here (https://github.com/node-red/node-red-dashboard/issues/569), Node-RED dashboard used old version of GridStack.  
This PR try to update GridStack version from 0.5.5 to 0.6.4.

### CODE REVIEW

**Comment by adumesny** [comment]
glad you got it working. looks like you were doing a lot of custom work before...

**Comment by dceejay** [comment]
Hi - when I try importing some old flows with multiple groups occasionally I see like this
image
where the widget is half the actual width....  If I try and move it or lock and unlock it bounces back to this size...  BUT if I change the overall group width up then down again - it restores to complete width again OK... 
(Also the dashboard itself renders ok in all cases so it's not fatal)

**Comment by HiroyasuNishiyama** [comment]
Hi.  While testing layout editor, I encountered similar problem.
This PR (https://github.com/node-red/node-red-dashboard/pull/580) is intended to solve the problem.
Does your environment include this fix?
If not included, could you see the grid element (`DIV` item ) causing the error has a class `grid-stack-6` (6 is a width of the grid)?

**Comment by dceejay** [comment]
Ah right - I had not merged them all together.

**Comment by dceejay** [comment]
All good - thanks

**Pull request merged**
