### PR TITLE
fix for #684 red crash on empty dropdown node

### PR DESCRIPTION
**Pull request by jha-sudo**
emitOptions.value never has the opportunity to be populated when left blank

### CODE REVIEW

**Comment by dceejay** [comment]
Many thanks for spotting this.

Hi are you able to click the cla ? (and be using the same email account as registered in github ) .
Otherwise I'm also happy to apply manually

**Comment by jha-sudo** [comment]
It's saying that I already signed it. There might be issues with my email address as I use an alias (+) for my github account email. 
image

**Comment by dceejay** [comment]
well github didn't like something... maybe just editing the PR will kick it to recheck. If not then may have to close and resubmit.

**Comment by Paul-Reed** [comment]
Maybe you need to sign the CLA again, using the alias email address that you used in your github account

**Comment by knolleary** [comment]
The email associated with the commits is already associated with the user https://github.com/jj-parxiti

If that is you, then you need to sign the cla as that user as well.

**Pull request closed without merging**
