### PR TITLE
Self hosted google material icon font

### LINKED ISSUE #549: [Suggestion] offline google material icons
### What are the steps to reproduce?

Watch network monitor in browsers dev mode.

### What happens?

Connection to google servers.

### What do you expect to happen?

No internet dependency.

### Please tell us about your environment:

Node-RED-Dashboard version: 2.18.0

### Possible solution

Serve google icon font like the other fonts bundled as offline font, e.g. fontawesome.

### PR DESCRIPTION
**Pull request by Rotzbua**
fix #549

not tested, just as a first try

### CODE REVIEW

**Comment by dceejay** [comment]
Thanks - yes at that size - well worth looking at.

**Comment by dceejay** [comment]
Great - when you have tested - can you accept the CLA so we can take a decent look at it ?
(and ideally provide a simple example also  - make life quicker :-)

**Comment by dceejay** [comment]
Looks really good - Many thanks.
Just wondering if we then drop the "angular-material-icons": "^0.7.1", dependency instead...
may need some other changes though.

**Comment by dceejay** [comment]
Hi @Rotzbua  - Is this still [WIP] or are you ok for me to merge it ?

**Comment by Rotzbua** [comment]
> Hi @Rotzbua - Is this still [WIP] or are you ok for me to merge it ?

It would be ok for me, but I dont have the time yet to test the code in a running nodered environment.

I found a problem: 
The path in the css to the font is currently wrong. It is `./fonts` and not `../fonts` as required.

>  Just wondering if we then drop the "angular-material-icons": "^0.7.1", dependency instead...

I guess this package is required for angular and does resolving and so on.

I think the `webfontloader` package can be droped because no other external font is loaded?

**Comment by dceejay** [comment]
Yes - having looked I think we do still need the angular-material-icons one for now in case any users happen to use it directly :-(. 
css - is that the generated file ? ie gulp task needs fixing ? or within the package itself ?

**Comment by Rotzbua** [comment]
* rebased the pr
* removed webfont loader.
* the path fix is added to the fontawesome fix file

Now it should work

**Comment by dceejay** [comment]
looks good here also ...  happy to merge if you are.

**Comment by Rotzbua** [comment]
> looks good here also ... happy to merge if you are.

yes

**Comment by dceejay** [comment]
Many thanks - I will update links in docs before release

**Comment by dceejay** [comment]
pushed back to  master.

**Pull request merged**
