### PR TITLE
Widget hide

### PR DESCRIPTION
**Pull request by hobbyquaker**
implements widget hiding with resizing (#177)

### CODE REVIEW

**Comment by dceejay** [comment]
As per discussion in #177 - can you target the "classy" branch please ? Thanks

**Comment by hobbyquaker** [comment]
But this has nothing to do with group-classes? This is widget-hiding with resize.

**Comment by dceejay** [comment]
Apologies. The groups thing is all about hiding and resizing also. 
If you want to PR again - then feel free - but I won't accept it into master :-)

**Comment by hobbyquaker** [comment]
Ok, understood :)

**Comment by dceejay** [comment]
feel free to re-target the branch

**Comment by dceejay** [comment]
ooo- - found out I can do that.. :-)

**Pull request closed without merging**
