### PR TITLE
Uses msg.timestamp as the time, if it is set.

### LINKED ISSUE #222: Custom msg timestamp for chart
Is it possible to set a custom timestamp on a msg that will be shown on the chart x-axis?
I've tried to set `msg.timestamp` but no success.

This would be highly appreciated since I'm trying to show a glucose chart with measures that need to be organized by their actual date, note the date that the msg was received by the `chart` node.

### PR DESCRIPTION
**Pull request by marciogranzotto**
This fixes #222. Let's the user add data that occurred on the past.

### CODE REVIEW

**Comment by dceejay** [comment]
Hi,

In general we prefer things to be discussed on the mailing list or slack first, but seeing as you have raised it already... Does this implementation solve the problem ? It just adds points to the end of the array - and so as long as the points arrive in time order all is well - but if not you can odd or unexpected results... eg lines drawn backwards in time
image

So should they be inserted into the array in the correct place... with all the implications of a large array sort has on performance ?
Also if you have set the time window to be last 1 minute (for example) and a message then arrives with a timestamp prior to that it will still get displayed...
So not going to merge as is until these have been discussed and thought about.

**Comment by shrickus** [comment]
I love this idea of having an inherent msg.timestamp field available for operations that deal with time-series data (charts, aggregators, delays, triggers). In several of my projects, that would be at least as important as using the well-understood msg.topic field to separate msgs by their purpose or originator. Of course, the current system timestamp would continue to be used by default, to avoid backwards compatibility issues with existing nodes/flows that don't set or use the msg.timestamp field.

The chart node should insert new "data points" in their correct position, based on the msg.timestamp field. I did a bit of research on how to efficiently implement that behavior, and found several npm libraries that could be used. One that looks promising is the [sorted-array](https://github.com/javascript/sorted-array) library, which is just over 2K in size. I also found an interesting description of the [Binary Insert](http://machinesaredigging.com/2014/04/27/binary-insert-how-to-keep-an-array-sorted-as-you-insert-data-in-it/) algorithm, which locates the proper insertion point faster than appending and re-sorting the whole array.

As for the question about whether to show newly arrived "old" data points: if the chart is only showing the last two hours of data (for instance) a quick check of the msg.timestamp would simply ignore this data if it was older than two hours, I would think. Likewise, if the limit is set to show 100 points, then the msg.timestamp would have to be compared to the timestamp of the first data point -- if it's older than that, it can safely be ignored (otherwise the oldest point would have to be shifted out and the new data point inserted).

This [JSPerf test page](https://jsperf.com/insert-into-sorted) shows how much faster inserting into a sorted array can be. It also provides a pretty compact implementation of some code to locate the proper insertion point. The two checks outlined above could be added to avoid modifying the array whenever the incoming timestamp would not be shown.

**Comment by marciogranzotto** [comment]
I've added binary insertion, but this is still not working properly. It seems that no matter what, the last value is emitted and rendered on the frontend, instead of the full array.

**Comment by dceejay** [comment]
Hi - you may have noticed (or not) that I am working n a chart3 branch... that now can handle inserting data correctly. 
(It also completely changes the data array being output and also the array for data input - so is currently a major breaking change... but does perform better as well.)

**Comment by jroux1** [comment]
👍👍👍👍👍

**Comment by clickworkorange** [comment]
I haven't spent much time with Node-RED yet, but though I'm mightily impressed by its speed and flexibility, this seems to me to be a major omission; the complete lack of a temporal dimension. Time awareness would make all sorts of exciting (time related) things possible: history, persistence, replayability, zooming, filtering, datalogging, exchange, aggregation, backups, comparisons... I've tried adding my own timestamps to messages but since they're only recognised by my own code their usefulness is limited. I realise this probably goes against some central paradigm of Node-RED's design, and its close link to MQTT, but here, I'll say it anyway: 

A standardised timestamp property which is passed around and acted on by all modules (where relevant), and which gets emitted and ingested to/from external datasources and message brokers would be ideal - but even just making the dashboard timestamp aware is a great addition!

**Comment by dceejay** [comment]
I think the key phrase there is "where relevant". Trying to get a set of barely smart disconnected sensors and processors to agree on what time it is has always been a problem. The only common agreement is "event happens now" - and the local device can then ascribe whatever value it wants to now. 
So yes when it comes to logs and looking back at old data time is critical, but I'm not sure how it fits (any more than being "just another" data field) in my message, which as you said yourself is easy to add. I'd be interested to see what other places you see it missing.

In the meantime I pushed a further fix to the chart3 branch.

**Comment by dceejay** [comment]
this update 5d20ac6f4fe37ea25201a41172f8cd01490e16a2 fixes this - so this PR no longer needed. Thanks for raising it and pushing us to fix it.

**Pull request closed without merging**
