### PR TITLE
New feature: hide and/or disable dashboard tabs

### PR DESCRIPTION
**Pull request by shrickus**
Allow individual tabs to be hidden from the Navigation Menu (but still active), or disabled (but still listed) in the Nav Menu. Setting both is required to effectively remove a tab from the Dashboard's UI.

### CODE REVIEW

**Comment by dceejay** [comment]
Errr - this says no files changed - what is this targeting ? Did you push it to your branch OK ?

**Comment by shrickus** [comment]
Wow, I know it was late last night, but i didn't even notice that the changes were not actually *commited* ...
sorry for the false alarm.

**Comment by dceejay** [comment]
just add them to this PR when you can :-)

**Comment by dceejay** [comment]
Better. I think maybe a line of text under icon line saying something like “Visibility in navigation menu” and then just the buttons Enabled/Disabled and Shown/Not shown ? Maybe ?

**Comment by dceejay** [comment]
Really getting there. - Do you want me to merge and play or you happy to keep tweaking ?
I think when disabled it should leave the icon as-is - and just set the colour grey - (maybe #808080)
image
We may have to have a light and dark version but let's try without first.

In the layout menu
image
I think maybe the text should grey for disabled (but leave icon) and then for hidden the icon should be the eye-slash but don't grey...  - and then both for both... does that make sense ?

**Comment by shrickus** [comment]
I'm happy for you to merge and do whatever cleanup is needed to make the look & feel consistent with the dashboard themes. I doubt I will have any time to tweak it until mid-next week, anyway.

My thought was to have it be obvious when the tab was just hidden from the Nav Menu -- I think the `eye-slash` icon is good for that. I like the line-through to show disabled (like it's been removed), but I agree it looks "odd" in the Nav Menu -- greyed out is more typical for the UI to show when a menu is "not available".

**Pull request merged**
