### PR TITLE
ui_dropdown.js, ui-component-ctrl.js

### PR DESCRIPTION
**Pull request by pelis**
ui_dropdown.js:
- moved code from beforeEmit() to convert()
- invalid options are now ignored
  - no message is sent
  - .error() is called instead

ui-component-ctrl.js
just did some formatting and typo changes - don't know why it seems to find that many changes...

test flow attached
[ui-dropdown_test.txt](https://github.com/node-red/node-red-dashboard/files/424686/ui-dropdown_test.txt)

- button one and two will try to send invalid options
- last button is a combination of option inputs 
  - value array containing strings and numbers
  - array of {label: value} objects

### CODE REVIEW

**Comment by dceejay** [comment]
Hi,

thanks for this - have merged. Have also tweaked it slightly so do pull it back before further editing. I added some info to the html, and overall readme. Moved the break outside the object parsing for loop, so it could handle multiple pairs as you suggested. And tidied up some linting - we do have a .jshintrc and .jscsrc we use to keep things in line :-)

More thoughts....
It does still output the object when the list is changed... Not sure this should happen - as it's not a result of a user selection ... ???  but...  should the ui not go back to ?
image


it now treats a single option as an error... again not sure this is correct. I may (as you point out in future use case ;-) feed one select from another  and the result may be that the second only has one option. The error was that it wasn't ouputing anything when the one thing was selected.

Did I see an option to set the default selected item ?  need to document that.

**Comment by pelis** [comment]
yes, I do pass the selected item of the new options list. So this behaves as if the user had selected that item. Your suggestion of setting the drop-down to “unselected” is probably a better idea, please feel free to modify that. However, in any event we should pass that on to the receiving node. If we would NOT pass that on to the receiving node then the app would be out of sync: e.g. data dependent on the selection would then still display the previously selected option - which may not even be there anymore. So please feel free to ‘unselect’ the dropdown.
And yes, if msg.selectItem is available, then selectItem is the selected value (forgot to add that to my test flow). In this case we should definitely set this as the new selection and pass it on.
if msg.selectItem is not available, then currently, the first item of the new options list is selected (as mentioned above an you suggest, we could also deselect the dropdown).

**Comment by pelis** [comment]
Do you want a new test-flow including msg.selectItem?

**Comment by pelis** [comment]
Forgot to reply to single option:
not exacly sure what you mean:
If you pass in - ['xxx'] or [{'l_xxx': 'xxx'}] that both should be accepted and should both be a single option.
In the code I am just checking whether payload is an array or not.
You may as well pass in an empty array [] which should remove all options (I must admit, I did not test this one - will do that right now...).

However, if you just pass in a value such as 'xxx' then I currently do not accept that.

**Comment by pelis** [comment]
clear options tested - OK
attached please find new test flow (including clear options and msg.selectItem
[ui-dropdown_test.txt](https://github.com/node-red/node-red-dashboard/files/425034/ui-dropdown_test.txt)

**Comment by dceejay** [comment]
aha - your first case sends {"value": "ValueNew", "label": "LabelNew"}   is of course an error as it's not an array... oops.
I just needed reminding of msg.selectItem - will give it a whirl.
And yes - would be happy sending things on a list change if "default" was unselected.... should that be payload null (object) or "" or what ??? (suggestions please). And then that would be overridden by msg.selectItem if set. 

BUT - I have change msg.selectItem to be msg.selectValue - as it's the Value that is required (as opposed to the Label)... 
Now changed like this and works great.... 

Only then begs the question...  should we allow an input of just msg.selectValue to dynamically change the selected value (ie without a change of options) ?

**Comment by pelis** [comment]
To your last point:
Yes, I thought about that, we could provide that in two ways:

1. as you suggested via msg.selectValue
2. just pass the value in payload (which now is not accepted and leads to error). We may as well treat this as a value change,  that's what I had in my very first code version.

Will look at that and the de-select, but won't be before next week...

**Comment by dceejay** [comment]
de-select is working (as I now set to null object by default - that then has effect of de-selecting the actual ui value).
Not sure about just accepting value - as it is then overloading msg.payload....   Unless of course we flip it all around... and always use msg.payload as the selected value... and use msg.options for the choices array...   doh ! can't make up my mind.

**Comment by natcl** [comment]
I like the latter.

**Comment by dceejay** [comment]
must admit - leaning that way. Will try changing it that way....

**Comment by dceejay** [comment]
Have pushed a version that now expects msg.options to be the array of options, and msg.payload to (pre)select the chosen value in the list. I'm liking it more now.
Also the output contains msg.fromInput rather than msg.isOptionsMsg as it set true for either options being set or the selected value being changed via the input.

**Comment by pelis** [comment]
I don't have any preferences - so feel free to do it the way you want.

Let me know if there is anything left you want me to do...

**Pull request merged**
