### PR TITLE
Multiple select for dropdown node

### PR DESCRIPTION
**Pull request by namgk**
Hi there,

I need this for a SQL builder and think it would be helpful.

image

It outputs an array of selected options once closed.

If there's only one selection, it will output the value instead, for backward compatibility.

### CODE REVIEW

**Comment by dceejay** [comment]
Hi - thanks for the idea. 
Currently your version is not exactly backwards compatible. For example if I open an existing select I see
image
and clicking an item selects it immediately and the select closes.
If I use your version I see
image
with a large white bar (what is that?)
and the tick boxes are not themed.
image
If I then select one there is no obvious way to finish the select ? You can't double click . and seem to have to click away somewhere ? Is this correct ?

If this is going to be an option then I think this behaviour should be optional - maybe selected via an extra option above here  
image
And if that is the case then I would suggest in that mode it could always return an array.

So yes the idea is OK in principle - but needs a bit more work. Thanks

**Comment by namgk** [comment]
Thanks @dceejay,

Due to the nature of multiple select, you can only "finish" a selection when you click to an outer space to close it. This is general form filling experience that is not related to Node RED. 

Surely I can work on a special mode, but do you think "having to close the selection" would break any functionality or just affect the user experience with the form?

The empty box is for filtering the search items. I can try to put up some label there, but there seems lack of space. I'll put up styling for the boxes as well.

**Comment by dceejay** [comment]
OK - re clicking - so yes makes me more sure we want this multi-select mode as a selectable option. 

If we do have to have the search box then it should be identified as such (fa-search icon as a prompt inside the search box maybe ?)  

The search box definitely needs to be styled both colour and spacing so the text isn't hard up to the left. Height could be smaller also.
image

**Comment by dceejay** [comment]
maybe something like 
image

**Comment by namgk** [comment]
How about something like this:

image

**Comment by dceejay** [comment]
I.d prefer icon than word as we don't have to translate it, but yes much better

**Comment by namgk** [comment]
Live and learn! I’ll follow your advice.

**Comment by dceejay** [comment]
yes - so far there is no fixed text at all on the ui side so users should be able to set everything themselves (AFAIK ;-) - and I don't feel the need to get into full translation mode for a single word, so yes please. Happy to re-look at code when you are ready.

**Comment by namgk** [comment]
Ok, here is how the latest changes look like:

image

image

**Comment by dceejay** [comment]
So close... now in single select mode we have
image

Not sure we want the search (in order to be backwards compliant)....

(though thinking out loud - actually maybe it would be nice in both cases IF we can detect the length is greater than (say) 10 - then to show the search bar - but don't for less than that. - What do you think ?)

**Comment by namgk** [comment]
It's done, not too perfect cause I cannot reuse one md-select while having the multiple attribute to be conditional with regard the option. Seems like an Angular thing ([example here](https://codepen.io/nhongk/pen/BaoJLyj?editable=true%3Dhttps%3A%2F%2Fmaterial.angularjs.org%2Flatest%2Fdemo%2Fselect)).

Thus, two separate md-select blocks.

I also revised the close handler for multiple select case, i.e. if there's no change, skip the update. In single case we don't have this closing logic cause the value is updated lively on changes.

**Comment by dceejay** [comment]
Thanks very much for this. Very useful contribution.

**Comment by namgk** [comment]
Thank you Dave.

**Comment by dceejay** [comment]
PS - I changed it to 7 before the menu appears as that seems to fit on mobile devices without scrolling (at least in portrait).
thanks again.

**Pull request merged**
