### PR TITLE
Improved german translations

### PR DESCRIPTION
**Pull request by fellinga**
Improved german translations

### CODE REVIEW

**Comment by fellinga** [comment]
We further improved the German translations and moved all _**data-help-name="ui_nodeName"**_ sections to separate files, so that they can be translated at any time.

**Comment by dceejay** [comment]
Hi - thanks - looks really good - will check it out more thoroughly later.
Several of the files seems to have jumped to 2 space indent rather than the default 4 we use.
But the moving to separate files is very welcome. Thanks

**Comment by fellinga** [comment]
Fixed indentation. 
@heikokue consider this for the core translation as well (if applicable)

**Comment by heikokue** [comment]
@fellinga thanks for your tip
@dceejay do we have a doc about the code format standard or a proposed tool/editor doing the formatation?

**Comment by dceejay** [comment]
there is a .jscsrc file in the root of this project that quite a few editor plugins will recognise.
(but thanks for the fixup)

**Comment by dceejay** [comment]
Many thanks - especially for the splitting out of the files.

**Pull request merged**
