### PR TITLE
Remove "!important" from all Component-Styles

### PR DESCRIPTION
**Pull request by patrickbruckner**
Removed all unneeded "!important" declaration from css files. Feel free to test your dashboards. Tested on local flows.

The Benefits of these changes is a better customisable dashboard through css.

### CODE REVIEW

**Comment by knolleary** [comment]
Could you provide some more information about this PR?

Have you tested it to verify all of the behaviour is the same once the `!important` declarations are removed? I assume they exist for a reason, so just removing them will likely break something unless you have restructured the CSS to ensure the rules apply where needed.

**Comment by patrickbruckner** [comment]
> Could you provide some more information about this PR?
> 
> Have you tested it to verify all of the behaviour is the same once the `!important` declarations are removed? I assume they exist for a reason, so just removing them will likely break something unless you have restructured the CSS to ensure the rules apply where needed.

I tested it on my own flows with manny different types and stacked nodes, but feel free to test it in more detail yourself.
The only thing these !important statements do, is make it harder to customize for Users that know CSS.

**Comment by dceejay** [comment]
Indeed some may be removeable - but some are not. So not going to accept as-is. Will take some time to go back through an review them all - so don't hold your breath.

**Comment by patrickbruckner** [comment]
> Indeed some may be removeable - but some are not. So not going to accept as-is. Will take some time to go back through and review them all - so don't hold your breath.

If it would help you approve it faster I could test the PR in greater detail to ensure everything still works. For Buttons, Switches, Sliders and other basic components I can already assure everything still works.

**Comment by dceejay** [comment]
Hi, yes it would help. Working is not the problem, its the alignment versus other items when in a variety of sizes and orientations.

**Comment by dceejay** [comment]
Hi - I have been through most of these now and have indeed removed most of them manually and applied most of them myself in [this commit](https://github.com/node-red/node-red-dashboard/commit/73f4f16462364bfe01a6599a5b15072209415d70)

There are some of the sizing ones we need to keep. and there are also probably more we could clean up - but this should address most of the ones you raised.

**Comment by dceejay** [comment]
Closing this as I think all the ones that this mention that can be addressed have been fixed already. Feel free to re-open with updates based on latest builds.

**Pull request closed without merging**
