### PR TITLE
Return 12:00:00 AM of date selected

### PR DESCRIPTION
**Pull request by johnwalicki**
Proposed fix for https://github.com/node-red/node-red-dashboard/issues/599

### CODE REVIEW

**Comment by daledj** [comment]
dceejay: Your fix for #599 was committed and merged in #600 however I'm running node red version 3.0.2, installed about a month ago and the fix does not appear to be present. The date picker does NOT return a time of 00:00:00. It returns the time of the last timestamp it received. Am I missing somthing?

**Comment by dceejay** [comment]
the fix does `.setUTCHours(0,0,0,0),`  so as you can see it should set it in UTC.

**Comment by daledj** [comment]
I do see the fix in the code here. However, that is not how it is acting in my copy  of node red version 3.0.2 installed in Windows 10. I'm wondering if the fix somehow never made it to the release? I have more information about this issue in this post: https://discourse.nodered.org/t/node-red-date-picker-issue/76567

**Comment by johnwalicki** [comment]
My patch is still in the code:

https://github.com/node-red/node-red-dashboard/blob/37b11b8bc0b4b7ab8206628a659def12201356fb/nodes/ui_date_picker.js#L27

**Pull request merged**
