### PR TITLE
Form node updated

### PR DESCRIPTION
**Pull request by dsl400**
Added input that allows users to fill the form 
Added multiline support for text input

### CODE REVIEW

**Comment by dceejay** [comment]
Saw your comment on forum asking about inout handling ... did you resolve that ? or is it still outstanding ?
Any chance you can remove the two conflicting files to make merging easier ? thanks

**Comment by dsl400** [comment]
Yes, the problem is solved.

**Comment by dceejay** [comment]
Hi I have merged this as-is - but there are a few things need fixing before release...
If I set multiline to 3
image
I currently (using default grid) looks like 5 lines, and the font color isn't picking up correctly...
image

**Comment by dceejay** [comment]
OK - have pushed fix for text colour css.

**Comment by dceejay** [comment]
And now understand the rows... it's UI rows not text rows... so have added that to docs
no need for changes.

**Comment by dsl400** [comment]
Wanting to stay up to date I downloaded the repository again and I think it has a little problem.
For some reason when creating a new form element and switching it to multiline the rows number input does not become visible but in my previously created node that already has a multiline element it is visible

**Comment by dceejay** [comment]
hmm yes - idea was to hide that control for all other input types as they can't be multi-line - but yes fails to kick in at start.

**Pull request merged**
